name: PublishDocumentation

on:
  push:
    branch: [main]
  release:
    types: [published]
  
jobs:
  deploy_docs:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Generate Jazzy Docs for all targets
      uses: sersoft-gmbh/swifty-docs-action@v1
      with:
        output: docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
