 name: Swift

 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

 jobs:
   test-on-macOS:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v2
     - name: Test on macOS
       run: >
         swift test
         --parallel
         --enable-test-discovery
    
   test-on-linux:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Test on Linux
       run: >
         swift test
         --parallel
         --enable-test-discovery
